### ISSUE TITLE
Template undefined not found! (latest NMDC DH LinkML file vs linkml datastructure branch)

### ISSUE THREAD

**Issue by turbomam** [cidgoh/DataHarmonizer#280]
I just 
- fetched the latest `cidgoh/DataHarmonizer`
- checked out the `linkml-datastructure` branch
- copied https://raw.githubusercontent.com/microbiomedata/sheets_and_friends/issue-92-pipe-sep/artifacts/nmdc_dh.yaml into `template/nmdc_dh/source/`
- ran `make all`

When I opened `linkml.html`, the following appeared in the `Template` status box:

> Template undefined not found!

And when I clicked on the `Template` status box, I got an empty `Change Template` pull down menu

**Comment by ddooley** [comment]
Yes, the very latest commit leaves some broken things.  I'll get the menu system back in order shortly. If you walk it back to previous commit you will see menu working, but none of the global variables have been eliminated, or any API work which is what the latest WIP commit has in it.

**Comment by turbomam** [comment]
OK. I can wait. Thanks.

**Comment by ddooley** [comment]
Hmm, I'm just trying it too.  I see from a run I started last night that it has an error of some kind on the  /nmdc_dh.yaml file.  It seems to get through the MIxS mixs.yaml spec no problem. Something to do with adding "rank"?

Key error is: ValueError:  Unknown argument: rank = 1

```
cd template/nmdc_dh ; python ../../script/linkml.py --input ../../template/nmdc_dh/source/nmdc_dh.yaml
Loading LinkML specification for ../../template/nmdc_dh/source/nmdc_dh.yaml
Traceback (most recent call last):
  File "../../script/linkml.py", line 75, in <module>
    mixs_sv = SchemaView(options.linkml_file)
  File "/Users/damion/anaconda3/lib/python3.7/site-packages/linkml_runtime/utils/schemaview.py", line 99, in __init__
    schema = load_schema_wrap(schema)
  File "/Users/damion/anaconda3/lib/python3.7/site-packages/linkml_runtime/utils/schemaview.py", line 54, in load_schema_wrap
    schema = yaml_loader.load(path, target_class=SchemaDefinition, **kwargs)
  File "/Users/damion/anaconda3/lib/python3.7/site-packages/linkml_runtime/loaders/yaml_loader.py", line 23, in load
    metadata=metadata)
  File "/Users/damion/anaconda3/lib/python3.7/site-packages/linkml_runtime/loaders/loader_root.py", line 62, in load_source
    target_class(**as_dict(data_as_dict)) if data_as_dict is not None else None
  File "<string>", line 48, in __init__
  File "/Users/damion/anaconda3/lib/python3.7/site-packages/linkml_runtime/linkml_model/meta.py", line 390, in __post_init__
    self._normalize_inlined_as_dict(slot_name="slots", slot_type=SlotDefinition, key_name="name", keyed=True)
  File "/Users/damion/anaconda3/lib/python3.7/site-packages/linkml_runtime/utils/yamlutils.py", line 100, in _normalize_inlined_as_dict
    self._normalize_inlined(slot_name, slot_type, key_name, keyed, False)
  File "/Users/damion/anaconda3/lib/python3.7/site-packages/linkml_runtime/utils/yamlutils.py", line 200, in _normalize_inlined
    form_1({k: v})
  File "/Users/damion/anaconda3/lib/python3.7/site-packages/linkml_runtime/utils/yamlutils.py", line 153, in form_1
    order_up(key, slot_type(**as_dict(raw_obj)))
  File "<string>", line 69, in __init__
  File "/Users/damion/anaconda3/lib/python3.7/site-packages/linkml_runtime/linkml_model/meta.py", line 736, in __post_init__
    super().__post_init__(**kwargs)
  File "/Users/damion/anaconda3/lib/python3.7/site-packages/linkml_runtime/linkml_model/meta.py", line 544, in __post_init__
    super().__post_init__(**kwargs)
  File "/Users/damion/anaconda3/lib/python3.7/site-packages/linkml_runtime/linkml_model/meta.py", line 309, in __post_init__
    super().__post_init__(**kwargs)
  File "/Users/damion/anaconda3/lib/python3.7/site-packages/linkml_runtime/utils/yamlutils.py", line 48, in __post_init__
    raise ValueError('\n'.join(messages))
ValueError:  Unknown argument: rank = 1
make: *** [template/nmdc_dh/schema.js] Error 1
```

**Comment by ddooley** [comment]
Its pretty quick to get to this error though for me, just seconds.  Do you folks have an updated nmdc_dh.yaml  file?

**Comment by turbomam** [comment]
> Key error is: ValueError: Unknown argument: rank = 1

Thanks. That is a newsish term in the meta-modelling language. You shouldn't get any more errors like that if you update linkml in your environment.

**Comment by turbomam** [comment]
running `script/linkml.py` against our nmdc_dh.yaml file works now. Thanks.
